# Generated by Django 3.0.5 on 2020-05-08 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_blogcomment_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomment',
            name='views',
        ),
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
